# Site settings
title: Nossos Vereadores - Campina
email: nazareno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Quem são nossos vereadores? O que fazem? Onde vivem, e do que se alimentam?.
baseurl: "/vereadorescg-site/" # the subpath of your site, e.g. /blog/
url: "http://nazareno.github.io" # the base hostname & protocol for your site
twitter_username: zananeno
github_username:  nazareno
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
